feat: CS-783 add workflow for container image build and push to ACR
Cofinity-X/entry-sldt-discovery-finder pull request #2
Opened 2024-05-30 10:59 UTC by niteshsakhiya

## Description
Added workflow for container image build and push to ACR

2024-05-31 07:09 UTC, bmunguli commented on .github/workflows/build-and-publish-image-acr.yml
> +  push:
I am a bit unsure about the trigger here if would be push to main for the entry repository. To my understanding we do not intent to develop features and interact with main that much and probably what ever change that we do should go primarily upstream and the main branch can get synched afterwards.

2024-05-31 07:41 UTC, niteshsakhiya commented on .github/workflows/build-and-publish-image-acr.yml
> +  push:
Yes. I was also unsure here. But thought of keeping it as it is possible that some of the services might require custom changes. 
I will now remove the on push trigger and later we can add it if needed.

2024-05-31 07:42 UTC, niteshsakhiya commented on .github/workflows/build-and-publish-image-acr.yml
> +  push:
Removed the trigger.

2024-05-31 08:09 UTC, bmunguli commented on .github/workflows/build-and-publish-image-acr.yml
> +    environment: acr-shared-env
same for the env here

2024-05-31 08:24 UTC, niteshsakhiya commented on .github/workflows/build-and-publish-image-acr.yml
> +    environment: acr-shared-env
Updated it. Thanks.

2024-05-31 09:42 UTC, bmunguli approved these changes

2024-05-31 12:11 UTC, typecastcloud requested changes
I would not push changed workflows into ENTRY repository main branch.

If we want to contribute we will have this as code change in PR to upstream

2024-05-31 12:18 UTC, bmunguli commented on .github/workflows/build-and-publish-image-acr.yml
> +  push:
Also another topic here: do we actually want to make changes in the main brach? 
We are considering a way to externalize probably the image building.

2024-06-03 04:47 UTC, niteshsakhiya commented
Alternate solution would be used instead of adding pipeline in the main branch.

2024-06-03 04:47 UTC, closed without merging